modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="creraces"
version="a1.0.4"
displayName="CreRaces"
credits="Choose a race!"
displayURL="https://www.instagram.com/saydagames/"
logoFile="logo.png"
authors="mc_jojo3"

[[dependencies.creraces]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




