plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    mixin {
        defaultRefmapName = "creraces-fabric.refmap.json"
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.property('1_21_1_fabric_api_version')}"
    modApi "dev.architectury:architectury-fabric:${rootProject.property('1_21_1_architectury_version')}"

    common(project(path: ":1.21.1:common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":1.21.1:common", configuration: "transformProductionFabric")) { transitive = false }
    implementation "com.google.code.findbugs:jsr305:3.0.2"

    // Twilight Lib - Direct File Dependency
    modImplementation files("${rootProject.projectDir.parentFile}/twilight-lib/1.21.1/fabric/build/libs/twilight_lib-1.21.1-fabric-${rootProject.twilight_lib_version}.jar")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":1.21.1:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
